[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "password-generator"
version = "0.1.0"
description = "Gerador de senhas seguras com interface CLI em argparse."
readme = "README.md"
requires-python = ">=3.10.5"
dependencies = []

[project.scripts]
password-gen-argparse = "main:main"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["cli_argparse", "generator", "main"]
